import { type Language, localize, numberLocale, type Localized } from './i18n'

export type { Localized } from './i18n'

export type DemoProduct = {
  id: string
  collection: 'culture' | 'ip'
  category: Localized
  title: Localized
  summary: Localized
  price: number
  stock: number
  image: string
  imageAlt: Localized
  story?: { src: string; alt: Localized }
  demo: true
}

export type DemoService = {
  id: string
  title: Localized
  summary: Localized
  deliverables: Localized[]
  demo: true
}

export type DemoCartLine = { productId: string; quantity: number }

export type DemoReceipt = {
  reference: string
  kind: 'order' | 'service'
  createdAt: string
  productIds?: string[]
  serviceId?: string
  projectDirection?: string
}

const product = (
  id: string, collection: DemoProduct['collection'], category: Localized, title: Localized,
  summary: Localized, price: number, stock: number, image: string, imageAlt: Localized,
  story?: DemoProduct['story'],
): DemoProduct => ({ id, collection, category, title, summary, price, stock, image, imageAlt, story, demo: true })

const media = '/assets/demo-market/products'

export const demoProducts: DemoProduct[] = [
  product('huali-craft-tray', 'culture', { en: 'Huali craft', zh: '花梨工艺' }, { en: 'Huali Grain Desk Tray', zh: '花梨纹理桌面托盘' }, { en: 'A Hainan-inspired desk object for a considered work ritual.', zh: '以海南花梨纹理为灵感的桌面器物，适合日常工作仪式。' }, 36, 18, `${media}/huali/product-huali-001-spec-placeholder.webp`, { en: 'Huali craft demo product visual', zh: '花梨工艺演示商品图' }, { src: '/assets/3d/products/huali/product-huali-001-poster.webp', alt: { en: 'Project 3D Huali study, not sales evidence', zh: '项目花梨 3D 研究图，不是销售凭证' } }),
  product('huali-scent-token', 'culture', { en: 'Huali craft', zh: '花梨工艺' }, { en: 'Huali Scent Token Set', zh: '花梨香气信物套装' }, { en: 'A small collectible concept that turns material memory into a travel keepsake.', zh: '将材质记忆转化为旅行纪念的轻量收藏概念。' }, 24, 26, `${media}/huali/product-huali-002-spec-placeholder.webp`, { en: 'Huali scent token demo product visual', zh: '花梨香气信物演示商品图' }),
  product('huali-postcard-case', 'culture', { en: 'Huali craft', zh: '花梨工艺' }, { en: 'Huali Postcard Case', zh: '花梨明信片收纳夹' }, { en: 'A presentation case concept for letters, tickets and Hainan visual fragments.', zh: '用于收纳书信、票根与海南视觉碎片的展示夹概念。' }, 29, 12, `${media}/huali/product-huali-003-spec-placeholder.webp`, { en: 'Huali postcard case demo product visual', zh: '花梨明信片收纳夹演示商品图' }),
  product('lijin-pattern-scarf', 'culture', { en: 'Li brocade', zh: '黎锦' }, { en: 'Li Pattern Travel Scarf', zh: '黎纹旅行围巾' }, { en: 'A bilingual pattern-study accessory inspired by the rhythm of Li textiles.', zh: '以黎锦节奏为灵感的双语纹样研究配饰。' }, 42, 21, `${media}/lijin/product-lijin-001-spec-placeholder.webp`, { en: 'Li pattern scarf demo product visual', zh: '黎纹围巾演示商品图' }, { src: '/assets/3d/products/lijin/product-lijin-001-poster.webp', alt: { en: 'Project 3D Li textile study, not sales evidence', zh: '项目黎锦 3D 研究图，不是销售凭证' } }),
  product('lijin-notebook', 'culture', { en: 'Li brocade', zh: '黎锦' }, { en: 'Li Pattern Field Notebook', zh: '黎纹田野笔记本' }, { en: 'A field-notes concept pairing travel writing with visual pattern references.', zh: '将旅行书写与纹样参考结合的田野笔记概念。' }, 16, 40, `${media}/lijin/product-lijin-002-spec-placeholder.webp`, { en: 'Li pattern notebook demo product visual', zh: '黎纹笔记本演示商品图' }),
  product('lijin-patch-set', 'culture', { en: 'Li brocade', zh: '黎锦' }, { en: 'Li Pattern Patch Set', zh: '黎纹布贴套装' }, { en: 'A collectible set designed for journals, travel bags and cultural exchange.', zh: '为手账、旅行包与文化交流设计的收藏布贴套装。' }, 12, 34, `${media}/lijin/product-lijin-003-spec-placeholder.webp`, { en: 'Li pattern patch set demo product visual', zh: '黎纹布贴套装演示商品图' }),
  product('tropical-atlas', 'culture', { en: 'Island ecology', zh: '海岛生态' }, { en: 'Tropical Island Field Atlas', zh: '热带海岛田野图册' }, { en: 'A visual travel atlas concept for reading coast, reef and rain forest together.', zh: '用于同时阅读海岸、珊瑚礁与雨林的视觉旅行图册概念。' }, 22, 30, `${media}/tropical/product-tropical-001-spec-placeholder.webp`, { en: 'Tropical island atlas demo product visual', zh: '热带海岛图册演示商品图' }, { src: '/assets/3d/products/village/product-village-001-poster.webp', alt: { en: 'Project 3D environment study, not sales evidence', zh: '项目 3D 环境研究图，不是销售凭证' } }),
  product('reef-light', 'culture', { en: 'Island ecology', zh: '海岛生态' }, { en: 'Reef Light Desk Object', zh: '珊瑚礁光影桌面摆件' }, { en: 'A small illuminated-object concept inspired by Hainan reef ecologies.', zh: '以海南珊瑚礁生态为灵感的小型光影摆件概念。' }, 34, 16, `${media}/tropical/product-tropical-002-spec-placeholder.webp`, { en: 'Reef light demo product visual', zh: '珊瑚礁光影摆件演示商品图' }),
  product('coast-card-set', 'culture', { en: 'Island ecology', zh: '海岛生态' }, { en: 'Hainan Coast Card Set', zh: '海南海岸明信片组' }, { en: 'A travel correspondence set shaped around the colours and edges of the island.', zh: '围绕海岛色彩与轮廓设计的旅行书信套装。' }, 14, 38, `${media}/tropical/product-tropical-003-spec-placeholder.webp`, { en: 'Hainan coast card set demo product visual', zh: '海南海岸明信片组演示商品图' }),
  product('village-tea-kit', 'culture', { en: 'Village journeys', zh: '乡村旅居' }, { en: 'Village Tea Pause Kit', zh: '乡村茶歇套装' }, { en: 'A slow-travel ritual kit concept for mapping a pause into a cultural journey.', zh: '将片刻休憩放入文化旅程的慢旅行仪式套装概念。' }, 28, 24, `${media}/village/product-village-001-spec-placeholder.webp`, { en: 'Village tea kit demo product visual', zh: '乡村茶歇套装演示商品图' }),
  product('village-map-print', 'culture', { en: 'Village journeys', zh: '乡村旅居' }, { en: 'Village Route Art Print', zh: '乡村路线艺术版画' }, { en: 'An illustrated route concept connecting local texture, seasons and walking pace.', zh: '连接地方质感、季节与步行节奏的插画路线概念。' }, 19, 20, `${media}/village/product-village-002-spec-placeholder.webp`, { en: 'Village route print demo product visual', zh: '乡村路线版画演示商品图' }),
  product('village-sound-kit', 'culture', { en: 'Village journeys', zh: '乡村旅居' }, { en: 'Village Sound Postcard Kit', zh: '乡音明信片套装' }, { en: 'A postcard concept for collecting the atmosphere of a place without claiming a recording.', zh: '收集地方氛围的明信片概念，不代表任何真实录音内容。' }, 18, 27, `${media}/village/product-village-003-spec-placeholder.webp`, { en: 'Village sound postcard kit demo product visual', zh: '乡音明信片套装演示商品图' }),
  product('luoyin-figure', 'ip', { en: 'Luoyin IP', zh: '螺音 IP' }, { en: 'Luoyin Explorer Figure', zh: '螺音探索者手办' }, { en: 'A project character collectible for the QIONGVERSE story world.', zh: '为琼境故事世界设计的项目角色收藏品。' }, 48, 15, '/assets/demo-market/ip/luoyin.png', { en: 'Luoyin project character demo product visual', zh: '螺音项目角色演示商品图' }),
  product('guardian-blind-box', 'ip', { en: 'Luoyin IP', zh: '螺音 IP' }, { en: 'Hidden Guardian Blind Box', zh: '守护灵隐藏款盲盒' }, { en: 'A concept blind-box edition from the Luoyin companion collection.', zh: '螺音伙伴系列的概念隐藏款盲盒。' }, 22, 9, '/assets/demo-market/ip/hidden-guardian.png', { en: 'Hidden Guardian demo product visual', zh: '守护灵演示商品图' }),
  product('luoyin-animation-license', 'ip', { en: 'Luoyin IP licensing', zh: '螺音 IP 授权' }, { en: 'Luoyin IP Copyright Licence', zh: '螺音 IP 版权授权' }, { en: 'A project demonstration of a copyright licence for the QIONGVERSE character system.', zh: '面向琼境角色系统的版权授权项目演示。' }, 200, 32, '/assets/demo-market/ip/luoyin-animation-library.jpg', { en: 'Luoyin IP copyright licensing demo visual', zh: '螺音 IP 版权授权演示图' }),
]

export const demoServices: DemoService[] = [
  { id: 'virtual-exhibition', title: { en: 'Virtual Exhibition Website', zh: '虚拟展厅网页制作' }, summary: { en: 'A bilingual exhibition destination for museums, venues and cultural businesses.', zh: '面向博物馆、场馆与文化企业的双语展厅网页。' }, deliverables: [{ en: 'Information architecture', zh: '信息架构' }, { en: 'Exhibition visual system', zh: '展厅视觉系统' }, { en: 'Bilingual visitor flow', zh: '双语访客流程' }], demo: true },
  { id: 'immersive-world', title: { en: 'Immersive Destination World', zh: '沉浸式景区大世界制作' }, summary: { en: 'A navigable spatial story for destinations, cultural districts and scenic routes.', zh: '面向景区、文旅街区与线路的可漫游空间叙事。' }, deliverables: [{ en: 'World concept', zh: '大世界概念' }, { en: 'Interactive journey', zh: '交互旅程' }, { en: 'Scene prototype', zh: '场景原型' }], demo: true },
  { id: 'digital-human-ip', title: { en: 'AI Digital Human and IP', zh: 'AI 数字人及 IP 形象制作' }, summary: { en: 'A character system connecting multilingual guidance, identity and content presence.', zh: '连接多语种导览、品牌身份与内容表达的角色系统。' }, deliverables: [{ en: 'Character direction', zh: '角色方向' }, { en: 'Interaction script', zh: '交互脚本' }, { en: 'Visual prototype', zh: '视觉原型' }], demo: true },
  { id: 'operations-promotion', title: { en: 'Operations and Cross-border Promotion', zh: '运营与跨境宣传' }, summary: { en: 'A practical content and campaign route for cultural reach across markets.', zh: '面向跨区域文化传播的内容与活动执行路径。' }, deliverables: [{ en: 'Audience route', zh: '受众路径' }, { en: 'Content calendar', zh: '内容节奏' }, { en: 'Campaign concept', zh: '传播活动概念' }], demo: true },
]

type CommerceLocale = Exclude<Language, 'en' | 'zh'>
type CommerceLocaleValues = Partial<Record<CommerceLocale, string>>
type CommerceHydration = {
  category?: CommerceLocaleValues
  title?: CommerceLocaleValues
  summary?: CommerceLocaleValues
  imageAlt?: CommerceLocaleValues
  storyAlt?: CommerceLocaleValues
  deliverables?: CommerceLocaleValues[]
}

/* These authored values complete the catalogue before any UI renders it. They
 * are explicit translations, so the generic legacy vocabulary never becomes a
 * public fallback for the market routes. */
const commerceHydration: Record<string, CommerceHydration> = {
  'huali-craft-tray': { category: { id: 'Kerajinan huali', ja: '花梨工芸', ko: '화리 공예', ru: 'Ремесло хуа-ли', ar: 'حِرف هُوالي' }, title: { id: 'Nampan meja serat huali', ja: '花梨木目のデスクトレー', ko: '화리 나뭇결 데스크 트레이', ru: 'Настольный поднос с узором хуа-ли', ar: 'صينية مكتبية بنقشة هُوالي' }, summary: { id: 'Benda meja berinspirasi serat huali Hainan untuk ritual kerja yang penuh perhatian.', ja: '海南の花梨の木目に着想を得た、丁寧な仕事の時間のためのデスクオブジェ。', ko: '하이난 화리 나뭇결에서 영감을 받은 사려 깊은 업무 의식용 책상 소품입니다.', ru: 'Настольный предмет с мотивом хайнаньского хуа-ли для вдумчивого рабочего ритуала.', ar: 'قطعة مكتبية مستوحاة من عروق خشب هُوالي في هاينان لطقس عمل متأنٍ.' }, imageAlt: { id: 'Visual demo produk kerajinan huali', ja: '花梨工芸のデモ商品ビジュアル', ko: '화리 공예 데모 상품 이미지', ru: 'Визуал демонстрационного изделия из хуа-ли', ar: 'صورة منتج تجريبي من حِرف هُوالي' }, storyAlt: { id: 'Kajian 3D huali proyek, bukan bukti penjualan', ja: 'プロジェクトの花梨3D研究、販売証拠ではありません', ko: '프로젝트 화리 3D 연구, 판매 증거 아님', ru: 'Проектное 3D-исследование хуа-ли, не подтверждение продажи', ar: 'دراسة ثلاثية الأبعاد لهُوالي من المشروع وليست دليلاً على البيع' } },
  'huali-scent-token': { category: { id: 'Kerajinan huali', ja: '花梨工芸', ko: '화리 공예', ru: 'Ремесло хуа-ли', ar: 'حِرف هُوالي' }, title: { id: 'Set kenang-kenangan aroma huali', ja: '花梨の香りのトークンセット', ko: '화리 향기 토큰 세트', ru: 'Набор ароматических талисманов хуа-ли', ar: 'مجموعة تذكارات برائحة هُوالي' }, summary: { id: 'Konsep koleksi kecil yang mengubah ingatan material menjadi kenang-kenangan perjalanan.', ja: '素材の記憶を旅の記念品に変える、小さなコレクションのコンセプト。', ko: '재료의 기억을 여행 기념품으로 바꾸는 작은 컬렉션 콘셉트입니다.', ru: 'Небольшая коллекционная концепция, превращающая память о материале в дорожный сувенир.', ar: 'مفهوم مقتنى صغير يحوّل ذاكرة الخامة إلى تذكار سفر.' }, imageAlt: { id: 'Visual demo token aroma huali', ja: '花梨の香りトークンのデモ商品ビジュアル', ko: '화리 향기 토큰 데모 상품 이미지', ru: 'Визуал демонстрационного ароматического талисмана хуа-ли', ar: 'صورة تذكار عطري تجريبي من هُوالي' } },
  'huali-postcard-case': { category: { id: 'Kerajinan huali', ja: '花梨工芸', ko: '화리 공예', ru: 'Ремесло хуа-ли', ar: 'حِرف هُوالي' }, title: { id: 'Kotak kartu pos huali', ja: '花梨のポストカードケース', ko: '화리 엽서 케이스', ru: 'Футляр для открыток из хуа-ли', ar: 'حافظة بطاقات بريدية من هُوالي' }, summary: { id: 'Konsep wadah untuk surat, tiket, dan fragmen visual Hainan.', ja: '手紙、チケット、海南の視覚的な断片を収めるプレゼンテーションケースのコンセプト。', ko: '편지, 티켓, 하이난의 시각적 조각을 담는 전시 케이스 콘셉트입니다.', ru: 'Концепция футляра для писем, билетов и визуальных фрагментов Хайнаня.', ar: 'مفهوم حافظة لعرض الرسائل والتذاكر والشذرات البصرية من هاينان.' }, imageAlt: { id: 'Visual demo kotak kartu pos huali', ja: '花梨のポストカードケースのデモビジュアル', ko: '화리 엽서 케이스 데모 이미지', ru: 'Визуал демонстрационного футляра для открыток из хуа-ли', ar: 'صورة حافظة بطاقات بريدية تجريبية من هُوالي' } },
  'lijin-pattern-scarf': { category: { id: 'Brocade Li', ja: '黎錦', ko: '리 브로케이드', ru: 'Ли-цзинь', ar: 'بروكار لي' }, title: { id: 'Syal perjalanan bermotif Li', ja: '黎族文様のトラベルスカーフ', ko: '리 문양 여행 스카프', ru: 'Дорожный шарф с узором ли', ar: 'وشاح سفر بنقوش لي' }, summary: { id: 'Aksesori studi pola dwibahasa yang terinspirasi ritme tekstil Li.', ja: '黎族織物のリズムに着想を得た、二言語の文様研究アクセサリー。', ko: '리족 직물의 리듬에서 영감을 받은 이중 언어 문양 연구 액세서리입니다.', ru: 'Двуязычный аксессуар-исследование узора, вдохновлённый ритмом тканей ли.', ar: 'إكسسوار لدراسة نقوش ثنائي اللغة مستوحى من إيقاع منسوجات لي.' }, imageAlt: { id: 'Visual demo syal bermotif Li', ja: '黎族文様スカーフのデモ商品ビジュアル', ko: '리 문양 스카프 데모 상품 이미지', ru: 'Визуал демонстрационного шарфа с узором ли', ar: 'صورة وشاح تجريبي بنقوش لي' }, storyAlt: { id: 'Kajian 3D tekstil Li proyek, bukan bukti penjualan', ja: 'プロジェクトの黎族織物3D研究、販売証拠ではありません', ko: '프로젝트 리족 직물 3D 연구, 판매 증거 아님', ru: 'Проектное 3D-исследование ткани ли, не подтверждение продажи', ar: 'دراسة ثلاثية الأبعاد لمنسوجات لي وليست دليلاً على البيع' } },
  'lijin-notebook': { category: { id: 'Brocade Li', ja: '黎錦', ko: '리 브로케이드', ru: 'Ли-цзинь', ar: 'بروكار لي' }, title: { id: 'Buku catatan lapangan bermotif Li', ja: '黎族文様のフィールドノート', ko: '리 문양 현장 노트', ru: 'Полевой блокнот с узором ли', ar: 'دفتر ملاحظات ميداني بنقوش لي' }, summary: { id: 'Konsep catatan lapangan yang memadukan tulisan perjalanan dengan referensi pola visual.', ja: '旅の文章と視覚的な文様資料を組み合わせるフィールドノートのコンセプト。', ko: '여행 기록과 시각적 문양 자료를 짝지은 현장 노트 콘셉트입니다.', ru: 'Концепция полевого блокнота, соединяющая дорожные записи и визуальные мотивы.', ar: 'مفهوم دفتر ميداني يجمع كتابة السفر مع مراجع النقوش البصرية.' }, imageAlt: { id: 'Visual demo buku catatan bermotif Li', ja: '黎族文様フィールドノートのデモビジュアル', ko: '리 문양 현장 노트 데모 이미지', ru: 'Визуал демонстрационного полевого блокнота с узором ли', ar: 'صورة دفتر ميداني تجريبي بنقوش لي' } },
  'lijin-patch-set': { category: { id: 'Brocade Li', ja: '黎錦', ko: '리 브로케이드', ru: 'Ли-цзинь', ar: 'بروكار لي' }, title: { id: 'Set patch bermotif Li', ja: '黎族文様ワッペンセット', ko: '리 문양 패치 세트', ru: 'Набор нашивок с узорами ли', ar: 'مجموعة رقع بنقوش لي' }, summary: { id: 'Set koleksi untuk jurnal, tas perjalanan, dan pertukaran budaya.', ja: '手帳、トラベルバッグ、文化交流のためにデザインしたコレクションワッペン。', ko: '다이어리, 여행 가방, 문화 교류를 위해 디자인한 컬렉션 패치 세트입니다.', ru: 'Коллекционный набор для дневников, дорожных сумок и культурного обмена.', ar: 'مجموعة مقتنيات صُممت للمذكرات وحقائب السفر والتبادل الثقافي.' }, imageAlt: { id: 'Visual demo set patch bermotif Li', ja: '黎族文様ワッペンセットのデモビジュアル', ko: '리 문양 패치 세트 데모 이미지', ru: 'Визуал демонстрационного набора нашивок с узорами ли', ar: 'صورة مجموعة رقع تجريبية بنقوش لي' } },
  'tropical-atlas': { category: { id: 'Ekologi pulau', ja: '島の生態', ko: '섬 생태', ru: 'Островная экология', ar: 'بيئة الجزيرة' }, title: { id: 'Atlas lapangan pulau tropis', ja: '熱帯島フィールドアトラス', ko: '열대 섬 현장 아틀라스', ru: 'Полевой атлас тропического острова', ar: 'أطلس ميداني للجزيرة الاستوائية' }, summary: { id: 'Konsep atlas visual untuk membaca pantai, terumbu, dan hutan hujan bersama.', ja: '海岸、サンゴ礁、熱帯雨林を一緒に読むためのビジュアル旅行アトラス。', ko: '해안, 산호초, 열대우림을 함께 읽는 시각 여행 아틀라스 콘셉트입니다.', ru: 'Концепция визуального атласа для совместного чтения побережья, рифа и дождевого леса.', ar: 'مفهوم أطلس سفر بصري لقراءة الساحل والشعاب والغابة المطيرة معاً.' }, imageAlt: { id: 'Visual demo atlas pulau tropis', ja: '熱帯島フィールドアトラスのデモビジュアル', ko: '열대 섬 현장 아틀라스 데모 이미지', ru: 'Визуал демонстрационного атласа тропического острова', ar: 'صورة أطلس ميداني تجريبي للجزيرة الاستوائية' }, storyAlt: { id: 'Kajian lingkungan 3D proyek, bukan bukti penjualan', ja: 'プロジェクトの3D環境研究、販売証拠ではありません', ko: '프로젝트 3D 환경 연구, 판매 증거 아님', ru: 'Проектное 3D-исследование среды, не подтверждение продажи', ar: 'دراسة ثلاثية الأبعاد لبيئة المشروع وليست دليلاً على البيع' } },
  'reef-light': { category: { id: 'Ekologi pulau', ja: '島の生態', ko: '섬 생태', ru: 'Островная экология', ar: 'بيئة الجزيرة' }, title: { id: 'Objek meja cahaya terumbu', ja: 'リーフライトのデスクオブジェ', ko: '산호초 빛 데스크 오브제', ru: 'Настольный объект «Свет рифа»', ar: 'قطعة مكتبية بضوء الشعاب' }, summary: { id: 'Konsep objek bercahaya kecil yang terinspirasi ekologi terumbu Hainan.', ja: '海南のサンゴ礁生態に着想を得た、小さな光るオブジェのコンセプト。', ko: '하이난 산호초 생태계에서 영감을 받은 작은 조명 오브제 콘셉트입니다.', ru: 'Концепция небольшого светового объекта, вдохновлённая рифовыми экосистемами Хайнаня.', ar: 'مفهوم قطعة مضيئة صغيرة مستوحاة من بيئات الشعاب في هاينان.' }, imageAlt: { id: 'Visual demo objek cahaya terumbu', ja: 'リーフライトのデモ商品ビジュアル', ko: '산호초 빛 데모 상품 이미지', ru: 'Визуал демонстрационного объекта «Свет рифа»', ar: 'صورة قطعة ضوء شعاب تجريبية' } },
  'coast-card-set': { category: { id: 'Ekologi pulau', ja: '島の生態', ko: '섬 생태', ru: 'Островная экология', ar: 'بيئة الجزيرة' }, title: { id: 'Set kartu pos pesisir Hainan', ja: '海南海岸ポストカードセット', ko: '하이난 해안 엽서 세트', ru: 'Набор открыток побережья Хайнаня', ar: 'مجموعة بطاقات بريدية لساحل هاينان' }, summary: { id: 'Set surat perjalanan yang dibentuk oleh warna dan tepian pulau.', ja: '島の色と輪郭を軸にデザインした、旅の手紙セット。', ko: '섬의 색과 가장자리에서 형태를 얻은 여행 편지 세트입니다.', ru: 'Набор дорожной переписки, созданный вокруг цветов и очертаний острова.', ar: 'مجموعة مراسلات سفر تشكلت حول ألوان الجزيرة وحوافها.' }, imageAlt: { id: 'Visual demo set kartu pos pesisir Hainan', ja: '海南海岸ポストカードセットのデモビジュアル', ko: '하이난 해안 엽서 세트 데모 이미지', ru: 'Визуал демонстрационного набора открыток побережья Хайнаня', ar: 'صورة مجموعة بطاقات ساحل هاينان التجريبية' } },
  'village-tea-kit': { category: { id: 'Perjalanan desa', ja: '農村の旅', ko: '농촌 여행', ru: 'Путешествия по деревням', ar: 'رحلات القرى' }, title: { id: 'Kit jeda teh desa', ja: '村のティーブレイクキット', ko: '마을 차 휴식 키트', ru: 'Набор для чайной паузы в деревне', ar: 'طقم استراحة شاي ريفية' }, summary: { id: 'Konsep ritual perjalanan lambat untuk menandai jeda dalam perjalanan budaya.', ja: '文化の旅にひと休みを描く、スロートラベルの儀式キット。', ko: '문화 여행 속 쉼표를 그려 보는 느린 여행 의식 키트 콘셉트입니다.', ru: 'Концепция ритуального набора медленного путешествия для обозначения паузы в культурном маршруте.', ar: 'مفهوم طقم طقس للسفر البطيء يرسم استراحة داخل رحلة ثقافية.' }, imageAlt: { id: 'Visual demo kit jeda teh desa', ja: '村のティーブレイクキットのデモビジュアル', ko: '마을 차 휴식 키트 데모 이미지', ru: 'Визуал демонстрационного набора для чайной паузы', ar: 'صورة طقم استراحة شاي ريفية تجريبية' } },
  'village-map-print': { category: { id: 'Perjalanan desa', ja: '農村の旅', ko: '농촌 여행', ru: 'Путешествия по деревням', ar: 'رحلات القرى' }, title: { id: 'Cetak seni rute desa', ja: '村のルートアートプリント', ko: '마을 경로 아트 프린트', ru: 'Арт-принт маршрута по деревне', ar: 'طبعة فنية لمسار ريفي' }, summary: { id: 'Konsep rute bergambar yang menghubungkan tekstur setempat, musim, dan ritme berjalan.', ja: '土地の質感、季節、歩く速度をつなぐイラストルートのコンセプト。', ko: '지역의 질감, 계절, 걷는 속도를 잇는 일러스트 경로 콘셉트입니다.', ru: 'Концепция иллюстрированного маршрута, соединяющего местную фактуру, сезоны и темп прогулки.', ar: 'مفهوم مسار مصوّر يصل بين ملمس المكان والفصول وإيقاع المشي.' }, imageAlt: { id: 'Visual demo cetak seni rute desa', ja: '村のルートアートプリントのデモビジュアル', ko: '마을 경로 아트 프린트 데모 이미지', ru: 'Визуал демонстрационного арт-принта деревенского маршрута', ar: 'صورة طبعة فنية لمسار ريفي تجريبية' } },
  'village-sound-kit': { category: { id: 'Perjalanan desa', ja: '農村の旅', ko: '농촌 여행', ru: 'Путешествия по деревням', ar: 'رحلات القرى' }, title: { id: 'Kit kartu pos suara desa', ja: '村の音ポストカードキット', ko: '마을 소리 엽서 키트', ru: 'Набор звуковых открыток деревни', ar: 'طقم بطاقات بريدية لأصوات القرية' }, summary: { id: 'Konsep kartu pos untuk mengumpulkan suasana tempat tanpa mengklaim rekaman nyata.', ja: '録音内容を主張せず、場所の空気を集めるポストカードのコンセプト。', ko: '실제 녹음이라고 주장하지 않고 장소의 분위기를 모으는 엽서 콘셉트입니다.', ru: 'Концепция открытки для сбора атмосферы места без заявления о реальной записи.', ar: 'مفهوم بطاقة بريدية لجمع أجواء المكان دون الادعاء بوجود تسجيل حقيقي.' }, imageAlt: { id: 'Visual demo kit kartu pos suara desa', ja: '村の音ポストカードキットのデモビジュアル', ko: '마을 소리 엽서 키트 데모 이미지', ru: 'Визуал демонстрационного набора звуковых открыток', ar: 'صورة طقم بطاقات أصوات القرية التجريبية' } },
  'luoyin-figure': { category: { id: 'IP Luoyin', ja: '螺音 IP', ko: '뤄인 IP', ru: 'IP Луоинь', ar: 'ملكية لويين' }, title: { id: 'Figur penjelajah Luoyin', ja: '螺音の探検者フィギュア', ko: '뤄인 탐험자 피규어', ru: 'Фигурка исследовательницы Луоинь', ar: 'مجسم مستكشفة لويين' }, summary: { id: 'Koleksi karakter proyek untuk dunia cerita QIONGVERSE.', ja: 'QIONGVERSEの物語世界のためのプロジェクトキャラクターコレクション。', ko: 'QIONGVERSE 이야기 세계를 위한 프로젝트 캐릭터 컬렉션입니다.', ru: 'Коллекционный персонаж проекта для сюжетного мира QIONGVERSE.', ar: 'مجسم شخصية من المشروع لعالم قصة QIONGVERSE.' }, imageAlt: { id: 'Visual demo karakter proyek Luoyin', ja: '螺音プロジェクトキャラクターのデモ商品ビジュアル', ko: '뤄인 프로젝트 캐릭터 데모 상품 이미지', ru: 'Визуал демонстрационной фигурки персонажа Луоинь', ar: 'صورة مجسم شخصية لويين التجريبي' } },
  'guardian-blind-box': { category: { id: 'IP Luoyin', ja: '螺音 IP', ko: '뤄인 IP', ru: 'IP Луоинь', ar: 'ملكية لويين' }, title: { id: 'Blind box Penjaga Tersembunyi', ja: '隠された守護者のブラインドボックス', ko: '숨은 수호자 블라인드 박스', ru: 'Слепая коробка «Скрытый хранитель»', ar: 'صندوق الحارس الخفي المفاجئ' }, summary: { id: 'Edisi blind box konseptual dari koleksi pendamping Luoyin.', ja: '螺音の仲間コレクションから生まれたブラインドボックスのコンセプト。', ko: '뤄인 동반자 컬렉션의 콘셉트 블라인드 박스 에디션입니다.', ru: 'Концептуальное издание слепой коробки из коллекции спутников Луоинь.', ar: 'إصدار مفاهيمي من صندوق المفاجآت ضمن مجموعة رفيقة لويين.' }, imageAlt: { id: 'Visual demo blind box Penjaga Tersembunyi', ja: '隠された守護者ブラインドボックスのデモビジュアル', ko: '숨은 수호자 블라인드 박스 데모 이미지', ru: 'Визуал демонстрационной слепой коробки «Скрытый хранитель»', ar: 'صورة صندوق الحارس الخفي التجريبية' } },
  'luoyin-animation-license': { category: { id: 'Lisensi IP Luoyin', ja: '螺音 IP ライセンス', ko: '뤄인 IP 라이선스', ru: 'Лицензирование IP Луоинь', ar: 'ترخيص ملكية لويين' }, title: { id: 'Lisensi hak cipta IP Luoyin', ja: '螺音 IP著作権ライセンス', ko: '뤄인 IP 저작권 라이선스', ru: 'Лицензия на авторские права IP Луоинь', ar: 'ترخيص حقوق نشر ملكية لويين' }, summary: { id: 'Demo proyek lisensi hak cipta untuk sistem karakter QIONGVERSE.', ja: 'QIONGVERSEキャラクターシステムの著作権ライセンスを示すプロジェクトデモ。', ko: 'QIONGVERSE 캐릭터 시스템을 위한 저작권 라이선스 프로젝트 데모입니다.', ru: 'Демонстрация проектной лицензии авторских прав для системы персонажей QIONGVERSE.', ar: 'عرض مشروع لترخيص حقوق نشر نظام شخصيات QIONGVERSE.' }, imageAlt: { id: 'Visual demo lisensi hak cipta IP Luoyin', ja: '螺音 IP著作権ライセンスのデモビジュアル', ko: '뤄인 IP 저작권 라이선스 데모 이미지', ru: 'Визуал демонстрации лицензии на авторские права IP Луоинь', ar: 'صورة عرض ترخيص حقوق نشر ملكية لويين' } },
  'virtual-exhibition': { title: { id: 'Situs pameran virtual', ja: 'バーチャル展示ウェブサイト', ko: '가상 전시 웹사이트', ru: 'Сайт виртуальной выставки', ar: 'موقع معرض افتراضي' }, summary: { id: 'Destinasi pameran dwibahasa untuk museum, ruang pamer, dan bisnis budaya.', ja: '美術館、会場、文化事業者向けのバイリンガル展示体験。', ko: '박물관, 전시장, 문화 기업을 위한 이중 언어 전시 공간입니다.', ru: 'Двуязычное выставочное пространство для музеев, площадок и культурного бизнеса.', ar: 'وجهة معرض ثنائية اللغة للمتاحف والقاعات والأعمال الثقافية.' }, deliverables: [{ id: 'Arsitektur informasi', ja: '情報アーキテクチャ', ko: '정보 구조', ru: 'Информационная архитектура', ar: 'هندسة المعلومات' }, { id: 'Sistem visual pameran', ja: '展示ビジュアルシステム', ko: '전시 시각 시스템', ru: 'Визуальная система выставки', ar: 'النظام البصري للمعرض' }, { id: 'Alur pengunjung dwibahasa', ja: 'バイリンガル来場者フロー', ko: '이중 언어 방문자 흐름', ru: 'Двуязычный путь посетителя', ar: 'مسار زائر ثنائي اللغة' }] },
  'immersive-world': { title: { id: 'Dunia destinasi imersif', ja: '没入型デスティネーションワールド', ko: '몰입형 목적지 월드', ru: 'Иммерсивный мир направления', ar: 'عالم وجهة غامر' }, summary: { id: 'Cerita ruang yang dapat dijelajahi untuk destinasi, distrik budaya, dan rute wisata.', ja: '目的地、文化地区、観光ルートのための歩いて巡れる空間ストーリー。', ko: '목적지, 문화 지구, 관광 경로를 위한 탐색 가능한 공간 이야기입니다.', ru: 'Пространственная история для направлений, культурных кварталов и туристических маршрутов.', ar: 'قصة مكانية قابلة للاستكشاف للوجهات والأحياء الثقافية والمسارات السياحية.' }, deliverables: [{ id: 'Konsep dunia', ja: 'ワールドコンセプト', ko: '월드 콘셉트', ru: 'Концепция мира', ar: 'مفهوم العالم' }, { id: 'Perjalanan interaktif', ja: 'インタラクティブな旅', ko: '인터랙티브 여정', ru: 'Интерактивное путешествие', ar: 'رحلة تفاعلية' }, { id: 'Prototipe adegan', ja: 'シーンプロトタイプ', ko: '장면 프로토타입', ru: 'Прототип сцены', ar: 'نموذج مشهد' }] },
  'digital-human-ip': { title: { id: 'Manusia digital AI dan IP', ja: 'AIデジタルヒューマンとIP', ko: 'AI 디지털 휴먼 및 IP', ru: 'ИИ-цифровой человек и IP', ar: 'إنسان رقمي وملكية بالذكاء الاصطناعي' }, summary: { id: 'Sistem karakter yang menghubungkan panduan multibahasa, identitas, dan kehadiran konten.', ja: '多言語ガイド、アイデンティティ、コンテンツ表現をつなぐキャラクターシステム。', ko: '다국어 안내, 정체성, 콘텐츠 표현을 연결하는 캐릭터 시스템입니다.', ru: 'Система персонажа, объединяющая многоязычный гид, идентичность и присутствие в контенте.', ar: 'نظام شخصية يصل بين الإرشاد متعدد اللغات والهوية وحضور المحتوى.' }, deliverables: [{ id: 'Arah karakter', ja: 'キャラクターディレクション', ko: '캐릭터 방향', ru: 'Направление персонажа', ar: 'توجيه الشخصية' }, { id: 'Skrip interaksi', ja: 'インタラクション台本', ko: '상호작용 스크립트', ru: 'Сценарий взаимодействия', ar: 'سيناريو التفاعل' }, { id: 'Prototipe visual', ja: 'ビジュアルプロトタイプ', ko: '비주얼 프로토타입', ru: 'Визуальный прототип', ar: 'نموذج بصري' }] },
  'operations-promotion': { title: { id: 'Operasi dan promosi lintas batas', ja: '運営と越境プロモーション', ko: '운영 및 국경 간 홍보', ru: 'Операции и трансграничное продвижение', ar: 'التشغيل والترويج عبر الحدود' }, summary: { id: 'Rute konten dan kampanye praktis untuk jangkauan budaya di berbagai pasar.', ja: '複数市場に文化を届けるための実践的なコンテンツとキャンペーンの道筋。', ko: '여러 시장에 문화를 전하기 위한 실용적 콘텐츠와 캠페인 경로입니다.', ru: 'Практический маршрут контента и кампаний для культурного охвата разных рынков.', ar: 'مسار عملي للمحتوى والحملات للوصول الثقافي عبر الأسواق.' }, deliverables: [{ id: 'Rute audiens', ja: 'オーディエンスルート', ko: '오디언스 경로', ru: 'Путь аудитории', ar: 'مسار الجمهور' }, { id: 'Kalender konten', ja: 'コンテンツカレンダー', ko: '콘텐츠 캘린더', ru: 'Контент-календарь', ar: 'تقويم المحتوى' }, { id: 'Konsep kampanye', ja: 'キャンペーンコンセプト', ko: '캠페인 콘셉트', ru: 'Концепция кампании', ar: 'مفهوم الحملة' }] },
}

const addCommerceLocales = (value: Localized, translations?: CommerceLocaleValues) => {
  if (!translations) return
  Object.assign(value, translations)
}

for (const entry of demoProducts) {
  const translation = commerceHydration[entry.id]
  if (!translation) continue
  addCommerceLocales(entry.category, translation.category)
  addCommerceLocales(entry.title, translation.title)
  addCommerceLocales(entry.summary, translation.summary)
  addCommerceLocales(entry.imageAlt, translation.imageAlt)
  if (entry.story) addCommerceLocales(entry.story.alt, translation.storyAlt)
}
for (const entry of demoServices) {
  const translation = commerceHydration[entry.id]
  if (!translation) continue
  addCommerceLocales(entry.title, translation.title)
  addCommerceLocales(entry.summary, translation.summary)
  translation.deliverables?.forEach((item, index) => addCommerceLocales(entry.deliverables[index], item))
}

export const tx = (language: Language, value: Localized) => localize(value, language)
export const formatDemoPrice = (language: Language, amount: number) => new Intl.NumberFormat(numberLocale(language), { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(amount)
