import type { Language, Localized } from './i18n'
export type { Language } from './i18n'

export type Zone = {
  id: string
  index: string
  title: Localized
  kicker: Localized
  description: Localized
  image: string
  thumbnail?: string
  mobileImage: string
  banner: string
  poster: string
  video?: string
  tag: Localized
  tone: 'tide' | 'woven' | 'amber' | 'village' | 'aerospace'
  guide: Localized
}

export const zones: Zone[] = [
  {
    id: 'tropical', index: '01', title: { en: 'Tropical Island Hall', zh: '热带海岛厅', id: 'Aula Pulau Tropis', ja: '熱帯海島展示室', ko: '열대 섬 전시관', ru: 'Зал тропического острова', ar: 'قاعة الجزيرة الاستوائية' },
    kicker: { en: 'A shoreline that keeps a record', zh: '一条保存记忆的海岸线', id: 'Garis pantai yang menyimpan jejak', ja: '記憶を刻む海岸線', ko: '기억을 간직한 해안선', ru: 'Береговая линия, хранящая память', ar: 'ساحل يحتفظ بذاكرته' },
    description: { en: 'Enter the tide line: mangrove shadows, salt air, and the slow rhythm of an island edge.', zh: '进入潮汐线：红树林的影子、盐的气息，以及岛屿边缘缓慢的节奏。', id: 'Masuki garis pasang: bayang bakau, udara asin, dan ritme pelan tepi pulau.', ja: '潮の境界へ。マングローブの影、潮の香り、島の縁のゆるやかなリズムを辿ります。', ko: '조수선으로 들어가 보세요. 맹그로브의 그림자, 짭조름한 공기, 섬 가장자리의 느린 리듬이 이어집니다.', ru: 'Войдите в линию прилива: тени мангров, солёный воздух и медленный ритм края острова.', ar: 'ادخل إلى خط المد: ظلال المانغروف والهواء المالح والإيقاع الهادئ لحافة الجزيرة.' },
    image: '/assets/user-media2/tropical-hall-banner-01.jpg', thumbnail: '/assets/home-thumbs/tropical.webp', mobileImage: '/assets/user-media2/tropical-hall-banner-01.jpg',
    banner: '/assets/user-media2/tropical-hall-banner-01.jpg', poster: '/assets/zones/tropical/zone-tropical-loop-poster.webp',
    tag: { en: 'REALITY / COAST', zh: '现实 / 海岸', id: 'REALITAS / PESISIR', ja: '現実 / 海岸', ko: '현실 / 해안', ru: 'РЕАЛЬНОСТЬ / ПОБЕРЕЖЬЕ', ar: 'الواقع / الساحل' }, tone: 'tide', guide: { en: 'I can hear the shoreline changing. Start with the coast, then follow the light.', zh: '我听见海岸正在变化。先从海边出发，再沿着光走。', id: 'Saya dapat mendengar garis pantai berubah. Mulailah dari pesisir, lalu ikuti cahaya.', ja: '海岸が変わる音が聞こえます。まず海辺から始め、光を追ってください。', ko: '변하는 해안선이 들립니다. 해안에서 시작해 빛을 따라가 보세요.', ru: 'Я слышу, как меняется берег. Начните с побережья и следуйте за светом.', ar: 'أسمع الساحل وهو يتغير. ابدأ من الشاطئ ثم اتبع الضوء.' },
  },
  {
    id: 'lijin', index: '02', title: { en: 'Li & Miao Intangible Heritage Hall', zh: '黎苗非遗厅', id: 'Aula Warisan Takbenda Li dan Miao', ja: '黎族・苗族無形文化遺産展示室', ko: '리·먀오 무형유산 전시관', ru: 'Зал нематериального наследия Ли и Мяо', ar: 'قاعة التراث غير المادي لشعبي لي ومياو' },
    kicker: { en: 'Patterns that remember', zh: '把记忆织进纹样', id: 'Pola yang mengingat', ja: '記憶する文様', ko: '기억하는 무늬', ru: 'Узоры, которые помнят', ar: 'نقوش تتذكر' },
    description: { en: 'Slow down with the rhythm of Li brocade: color, geometry, touch, and the people who keep making.', zh: '跟随黎锦的节奏慢下来：颜色、几何、触感，以及持续创造的人们。', id: 'Perlambat langkah bersama irama brokat Li: warna, geometri, sentuhan, dan para pembuatnya.', ja: '黎錦のリズムに合わせて立ち止まり、色、幾何、手触り、作り続ける人びとに目を向けます。', ko: '리 브로케이드의 리듬과 함께 천천히 살펴보세요. 색, 기하, 촉감, 그리고 계속 만드는 사람들의 이야기입니다.', ru: 'Замедлитесь в ритме парчи Ли: цвет, геометрия, прикосновение и люди, продолжающие создавать.', ar: 'تمهّل مع إيقاع نسيج لي: اللون والهندسة والملمس والناس الذين يواصلون الصنع.' },
    image: '/assets/user-media2/limiao-hall-banner-01.jpg', thumbnail: '/assets/home-thumbs/limiao.webp', mobileImage: '/assets/user-media2/limiao-hall-banner-01.jpg',
    banner: '/assets/user-media2/limiao-hall-banner-01.jpg', poster: '/assets/zones/lijin/zone-lijin-loop-poster.webp',
    tag: { en: 'REALITY / HERITAGE', zh: '现实 / 文化', id: 'REALITAS / WARISAN', ja: '現実 / 遺産', ko: '현실 / 유산', ru: 'РЕАЛЬНОСТЬ / НАСЛЕДИЕ', ar: 'الواقع / التراث' }, tone: 'woven', guide: { en: 'This pattern is not a decoration to rush past. Let us look at its structure first, then ask what has been carried through it.', zh: '这不是一眼掠过的装饰。让我们先看它的结构，再问它承载了什么。', id: 'Pola ini bukan hiasan untuk dilewati cepat. Mari lihat strukturnya, lalu tanyakan apa yang dibawanya.', ja: 'この文様は急いで通り過ぎる装飾ではありません。まず構造を見て、そこに何が託されているかを考えましょう。', ko: '이 무늬는 스쳐 지나갈 장식이 아닙니다. 먼저 구조를 보고 무엇이 담겨 있는지 물어보세요.', ru: 'Этот узор не украшение, которое стоит быстро пройти. Сначала рассмотрим его структуру, затем спросим, что он несёт.', ar: 'هذا النمط ليس زينة لنتجاوزها سريعاً. فلننظر أولاً إلى بنيته، ثم نسأل عمّا يحمله.' },
  },
  {
    id: 'aerospace', index: '03', title: { en: 'Wenchang Aerospace Hall', zh: '文昌航天厅', id: 'Aula Kedirgantaraan Wenchang', ja: '文昌宇宙開発展示室', ko: '원창 우주항공 전시관', ru: 'Аэрокосмический зал Вэньчан', ar: 'قاعة ونتشانغ للفضاء' },
    kicker: { en: 'A project-curated launch horizon', zh: '项目策展的发射地平线', id: 'Cakrawala peluncuran yang dikurasi proyek', ja: 'プロジェクトが編む打ち上げの地平線', ko: '프로젝트가 큐레이션한 발사 지평선', ru: 'Кураторский горизонт запуска проекта', ar: 'أفق إطلاق قيّمي من المشروع' },
    description: { en: 'A visual orientation room for Wenchang aerospace stories, assembled from project-supplied media and open-ended questions.', zh: '一间关于文昌航天叙事的视觉导览厅，使用项目提供的媒体素材，保留继续探索与提问的空间。', id: 'Ruang orientasi visual untuk kisah kedirgantaraan Wenchang, tersusun dari media proyek dan pertanyaan terbuka.', ja: 'プロジェクト提供の映像と開かれた問いから構成する、文昌の宇宙開発物語への視覚的な案内室です。', ko: '프로젝트 제공 미디어와 열린 질문으로 구성한 원창 우주항공 이야기의 시각 안내 공간입니다.', ru: 'Зал визуальной ориентации по аэрокосмическим историям Вэньчана, составленный из материалов проекта и открытых вопросов.', ar: 'قاعة توجيه بصري لقصص ونتشانغ الفضائية، مكوّنة من وسائط المشروع وأسئلة مفتوحة.' },
    image: '/assets/user-media2/media2/图片素材新/wenchang-hall-banner-01.jpg', thumbnail: '/assets/home-thumbs/aerospace.webp', mobileImage: '/assets/user-media2/media2/图片素材新/wenchang-hall-banner-01.jpg',
    banner: '/assets/user-media2/space-console/发射体验控制台.png', poster: '/assets/3d/aerospace/文昌航天展厅参考图.png',
    tag: { en: 'PROJECT / AEROSPACE', zh: '项目 / 航天', id: 'PROYEK / ANTARIKSA', ja: 'プロジェクト / 宇宙開発', ko: '프로젝트 / 우주항공', ru: 'ПРОЕКТ / КОСМОС', ar: 'المشروع / الفضاء' }, tone: 'aerospace', guide: { en: 'This is a project-curated visual layer. Ask for sources before treating any aerospace detail as current fact.', zh: '这是项目策展的视觉层。涉及航天细节时，请先查看来源，再将其理解为当前事实。', id: 'Ini adalah lapisan visual kurasi proyek. Periksa sumber sebelum menganggap detail kedirgantaraan sebagai fakta terkini.', ja: 'これはプロジェクトがキュレーションした視覚レイヤーです。宇宙開発の詳細を現在の事実と扱う前に、出典を確認してください。', ko: '이것은 프로젝트가 큐레이션한 시각 레이어입니다. 우주항공 세부 내용을 현재 사실로 받아들이기 전에 출처를 확인하세요.', ru: 'Это визуальный слой, курируемый проектом. Прежде чем считать аэрокосмические детали текущими фактами, проверьте источники.', ar: 'هذه طبقة بصرية قيّمية للمشروع. تحقق من المصادر قبل التعامل مع أي تفاصيل فضائية كحقائق حالية.' },
  },
  {
    id: 'huali', index: '04', title: { en: 'Dongfang Rosewood Hall', zh: '东方花梨厅', id: 'Aula Kayu Mawar Dongfang', ja: '東方花梨展示室', ko: '둥팡 화리목 전시관', ru: 'Зал палисандра Дунфан', ar: 'قاعة خشب الورد في دونغفانغ' },
    kicker: { en: 'The memory inside wood', zh: '木头里的时间', id: 'Ingatan di dalam kayu', ja: '木の中の記憶', ko: '나무 안의 기억', ru: 'Память внутри дерева', ar: 'الذاكرة داخل الخشب' },
    description: { en: 'A quiet room of grain, carving and material intelligence. Turn the object slowly; every surface changes the light.', zh: '一间关于木纹、雕刻与材料智慧的安静展室。慢慢转动作品，每一面都会改变光。', id: 'Ruang hening tentang serat, ukiran, dan kecerdasan material. Putar objek perlahan; setiap sisi mengubah cahaya.', ja: '木目、彫刻、素材の知性をめぐる静かな展示室です。ゆっくり回すと、どの面でも光が変わります。', ko: '결, 조각, 재료의 지성을 다루는 고요한 전시실입니다. 천천히 돌려 보면 모든 면에서 빛이 달라집니다.', ru: 'Тихий зал о текстуре, резьбе и интеллекте материала. Поворачивайте объект медленно: каждая поверхность меняет свет.', ar: 'قاعة هادئة عن العروق والنحت وذكاء المادة. أدر القطعة ببطء؛ فكل سطح يغيّر الضوء.' },
    image: '/assets/user-media2/huali-hall-banner-01.jpg', thumbnail: '/assets/home-thumbs/huali.webp', mobileImage: '/assets/user-media2/huali-hall-banner-01.jpg',
    banner: '/assets/user-media2/huali-hall-banner-01.jpg', poster: '/assets/zones/huali/zone-huali-loop-poster.webp',
    tag: { en: 'REALITY / CRAFT', zh: '现实 / 工艺', id: 'REALITAS / KRIYA', ja: '現実 / 工芸', ko: '현실 / 공예', ru: 'РЕАЛЬНОСТЬ / РЕМЕСЛО', ar: 'الواقع / الحرفة' }, tone: 'amber', guide: { en: 'Quiet here. The wood remembers through its grain. The ShellSong story around it is a fictional layer, not a historical claim.', zh: '这里需要安静。木头通过纹理记忆。围绕它的螺音故事是虚构叙事，不是历史断言。', id: 'Di sini tenang. Kayu mengingat melalui seratnya. Kisah ShellSong di sekelilingnya adalah lapisan fiksi, bukan klaim sejarah.', ja: 'ここでは静かに。木は木目を通して記憶します。周囲の ShellSong の物語は虚構のレイヤーであり、歴史的主張ではありません。', ko: '이곳은 고요합니다. 나무는 결을 통해 기억합니다. 이를 둘러싼 ShellSong 이야기는 역사적 주장이 아닌 허구의 레이어입니다.', ru: 'Здесь тихо. Дерево помнит через свою текстуру. История ShellSong вокруг него - вымышленный слой, а не историческое утверждение.', ar: 'هنا هدوء. يتذكر الخشب عبر عروقه. وقصة ShellSong حوله طبقة خيالية وليست ادعاءً تاريخياً.' },
  },
  {
    id: 'village', index: '05', title: { en: 'Beautiful Villages Hall', zh: '美丽乡村厅', id: 'Aula Desa Indah', ja: '美しい農村展示室', ko: '아름다운 농촌 전시관', ru: 'Зал красивых деревень', ar: 'قاعة القرى الجميلة' },
    kicker: { en: 'Where memory still lives', zh: '记忆仍在生活里', id: 'Tempat ingatan masih hidup', ja: '記憶が今も暮らす場所', ko: '기억이 여전히 살아 있는 곳', ru: 'Где память продолжает жить', ar: 'حيث لا تزال الذاكرة حية' },
    description: { en: 'Look closer at volcanic stone, fields, pathways and everyday gestures that make a place more than a view.', zh: '看见火山石、田野、路径与日常动作，让地方不止是一幅风景。', id: 'Perhatikan batu vulkanik, ladang, jalan setapak, dan gerak sehari-hari yang menjadikan tempat lebih dari sekadar pemandangan.', ja: '火山岩、畑、道、日々のしぐさを近くで見つめ、場所を風景以上のものにする要素を読みます。', ko: '화산석, 들판, 길, 일상의 몸짓을 가까이 보세요. 장소를 풍경 이상으로 만드는 것들입니다.', ru: 'Рассмотрите вулканический камень, поля, тропы и повседневные жесты, благодаря которым место становится больше, чем видом.', ar: 'تأمل الحجر البركاني والحقول والمسارات وإيماءات الحياة اليومية التي تجعل المكان أكثر من مجرد منظر.' },
    image: '/assets/user-media2/village-hall-banner-01.jpg', thumbnail: '/assets/home-thumbs/village.webp', mobileImage: '/assets/user-media2/village-hall-banner-01.jpg',
    banner: '/assets/user-media2/village-hall-banner-01.jpg', poster: '/assets/zones/village/zone-village-loop-poster.webp',
    tag: { en: 'REALITY / LIVING', zh: '现实 / 生活', id: 'REALITAS / KEHIDUPAN', ja: '現実 / 暮らし', ko: '현실 / 생활', ru: 'РЕАЛЬНОСТЬ / ЖИЗНЬ', ar: 'الواقع / الحياة' }, tone: 'village', guide: { en: 'A village is not a backdrop. Listen for the small routines that make a place feel held.', zh: '乡村不是背景。听一听那些让地方被好好守护的日常。', id: 'Desa bukan sekadar latar. Dengarkan rutinitas kecil yang membuat sebuah tempat terasa terawat.', ja: '村は背景ではありません。その場所を支える小さな日常の営みに耳を澄ませてください。', ko: '마을은 배경이 아닙니다. 장소를 지켜 주는 작은 일상의 리듬에 귀 기울여 보세요.', ru: 'Деревня - не фон. Прислушайтесь к маленьким привычкам, благодаря которым место ощущается сохранённым.', ar: 'القرية ليست خلفية. أنصت إلى العادات الصغيرة التي تجعل المكان يبدو محفوظاً ومحتضناً.' },
  },
]

type SiteCopy = { nav: string[]; menuLabel: string; heroEyebrow: string; heroTitle: string; heroBody: string; enter: string; listen: string; zonesEyebrow: string; zonesTitle: string; zonesBody: string; guideTitle: string; guideBody: string; guideWelcome: string; guideInput: string; send: string; source: string; reality: string; myth: string; mock: string; close: string; open: string; footer: string }

export const copy: Record<Language, SiteCopy> = {
  en: { nav: ['Home', 'Virtual Exhibition', 'Free Trade Port Reading Room'], menuLabel: 'Open exhibition menu', heroEyebrow: 'HAINAN∞QIONGVERSE / HAINAN PROVINCE', heroTitle: 'The island is speaking.', heroBody: 'A living digital exhibition of Hainan coastlines, cultural memory, craft and village life.', enter: 'Enter exhibition', listen: 'Listen with Luoyin', zonesEyebrow: 'TIDE ARCHIVE / FIVE HALLS', zonesTitle: 'Five ways into Hainan', zonesBody: 'Move through Hainan at the speed of a tide. Each hall holds a different way of reading the province.', guideTitle: 'Luoyin is listening', guideBody: 'Ask about a zone, a material, or the feeling you want to take with you.', guideWelcome: 'Begin anywhere. I will keep this conversation here while the chat window stays open.', guideInput: 'Ask Luoyin something...', send: 'Send', source: 'Supplied project asset', reality: 'Reality layer', myth: 'ShellSong myth', mock: 'Local guide preview', close: 'Close guide', open: 'Open Luoyin guide', footer: 'A living gateway to Hainan Province.' },
  zh: { nav: ['首页', '虚拟展厅', '自贸港阅览室'], menuLabel: '打开展厅菜单', heroEyebrow: 'HAINAN∞QIONGVERSE / 海南省', heroTitle: '岛屿正在说话。', heroBody: '一座关于海南热带海岸、文化记忆、手工艺与乡村生活的数字展厅。', enter: '进入展厅', listen: '与螺音一起聆听', zonesEyebrow: '潮汐档案 / 五个分展厅', zonesTitle: '进入海南的五种方式', zonesBody: '以潮汐的速度穿过海南。每一间展厅，都保存着不同的阅读方式。', guideTitle: '螺音正在聆听', guideBody: '可以问我展区、材料，或者你想带走的感觉。', guideWelcome: '从任何问题开始。对话框保持打开时，我会在这里保留这段对话。', guideInput: '问螺音一个问题……', send: '发送', source: '项目提供素材', reality: '现实层', myth: '螺音神话层', mock: '本地导览预览', close: '关闭导览', open: '打开螺音导览', footer: '一座通往海南省的活态入口。' },
  id: { nav: ['Beranda', 'Pameran Virtual', 'Ruang Baca Pelabuhan Perdagangan Bebas'], menuLabel: 'Buka menu pameran', heroEyebrow: 'HAINAN∞QIONGVERSE / PROVINSI HAINAN', heroTitle: 'Pulau ini sedang berbicara.', heroBody: 'Pameran digital hidup tentang pesisir Hainan, ingatan budaya, kriya, dan kehidupan desa.', enter: 'Masuk pameran', listen: 'Dengarkan bersama Luoyin', zonesEyebrow: 'ARSIP PASANG / LIMA AULA', zonesTitle: 'Lima jalan menuju Hainan', zonesBody: 'Jelajahi Hainan seirama pasang. Setiap aula menawarkan cara berbeda untuk membaca provinsi ini.', guideTitle: 'Luoyin sedang mendengarkan', guideBody: 'Tanyakan tentang aula, material, atau kesan yang ingin Anda bawa pulang.', guideWelcome: 'Mulailah dari pertanyaan apa pun. Selama jendela obrolan tetap terbuka, percakapan ini akan tetap di sini.', guideInput: 'Tanyakan sesuatu kepada Luoyin...', send: 'Kirim', source: 'Aset proyek yang disediakan', reality: 'Lapisan kenyataan', myth: 'Mitos ShellSong', mock: 'Pratinjau pemandu lokal', close: 'Tutup pemandu', open: 'Buka pemandu Luoyin', footer: 'Gerbang hidup menuju Provinsi Hainan.' },
  ja: { nav: ['ホーム', 'バーチャル展示', '自由貿易港リーディングルーム'], menuLabel: '展示メニューを開く', heroEyebrow: 'HAINAN∞QIONGVERSE / 海南省', heroTitle: '島が語りかけている。', heroBody: '海南の海岸、文化の記憶、工芸、村の暮らしを巡る生きたデジタル展示。', enter: '展示へ入る', listen: '螺音と聴く', zonesEyebrow: '潮汐アーカイブ / 五つの展示室', zonesTitle: '海南へ入る五つの方法', zonesBody: '潮の速度で海南を巡ります。各展示室には、海南を読む異なる方法があります。', guideTitle: '螺音が聴いています', guideBody: '展示室、素材、持ち帰りたい感覚について尋ねてください。', guideWelcome: 'どんな質問からでも始められます。チャットを開いている間、この会話をここに残します。', guideInput: '螺音に質問する...', send: '送信', source: 'プロジェクト提供素材', reality: 'リアリティ層', myth: 'ShellSong の神話', mock: 'ローカルガイドのプレビュー', close: 'ガイドを閉じる', open: '螺音ガイドを開く', footer: '海南省へ続く生きた入口。' },
  ko: { nav: ['홈', '가상 전시', '자유무역항 열람실'], menuLabel: '전시 메뉴 열기', heroEyebrow: 'HAINAN∞QIONGVERSE / 하이난성', heroTitle: '섬이 말을 건넵니다.', heroBody: '하이난의 해안, 문화적 기억, 공예와 마을의 삶을 담은 살아 있는 디지털 전시입니다.', enter: '전시 입장', listen: '뤄인과 함께 듣기', zonesEyebrow: '조수 아카이브 / 다섯 전시관', zonesTitle: '하이난으로 들어가는 다섯 길', zonesBody: '조수의 속도로 하이난을 지나갑니다. 각 전시관은 성을 읽는 다른 방식을 담고 있습니다.', guideTitle: '뤄인이 듣고 있습니다', guideBody: '전시관, 재료 또는 간직하고 싶은 감각을 물어보세요.', guideWelcome: '어떤 질문으로든 시작해 보세요. 대화창을 열어 두는 동안 이 대화를 여기에 남겨 둘게요.', guideInput: '뤄인에게 질문하기...', send: '보내기', source: '프로젝트 제공 자산', reality: '현실 레이어', myth: '셸송 신화', mock: '로컬 가이드 미리보기', close: '가이드 닫기', open: '뤄인 가이드 열기', footer: '하이난성으로 향하는 살아 있는 관문.' },
  ru: { nav: ['Главная', 'Виртуальная выставка', 'Читальный зал порта свободной торговли'], menuLabel: 'Открыть меню выставки', heroEyebrow: 'HAINAN∞QIONGVERSE / ПРОВИНЦИЯ ХАЙНАНЬ', heroTitle: 'Остров говорит.', heroBody: 'Живая цифровая выставка о побережьях Хайнаня, культурной памяти, ремесле и сельской жизни.', enter: 'Войти на выставку', listen: 'Слушать вместе с Луоинь', zonesEyebrow: 'АРХИВ ПРИЛИВОВ / ПЯТЬ ЗАЛОВ', zonesTitle: 'Пять путей в Хайнань', zonesBody: 'Путешествуйте по Хайнаню в ритме прилива. Каждый зал предлагает свой способ прочитать провинцию.', guideTitle: 'Луоинь слушает', guideBody: 'Спросите о зале, материале или впечатлении, которое хотите сохранить.', guideWelcome: 'Начните с любого вопроса. Пока окно чата открыто, я сохраню этот разговор здесь.', guideInput: 'Спросите Луоинь...', send: 'Отправить', source: 'Материал проекта', reality: 'Слой реальности', myth: 'Миф ShellSong', mock: 'Локальный предварительный гид', close: 'Закрыть гид', open: 'Открыть гид Луоинь', footer: 'Живой вход в провинцию Хайнань.' },
  ar: { nav: ['الرئيسية', 'المعرض الافتراضي', 'غرفة قراءة ميناء التجارة الحرة'], menuLabel: 'فتح قائمة المعرض', heroEyebrow: 'HAINAN∞QIONGVERSE / مقاطعة هاينان', heroTitle: 'الجزيرة تتحدث.', heroBody: 'معرض رقمي حي عن سواحل هاينان وذاكرتها الثقافية وحرفها وحياة قراها.', enter: 'دخول المعرض', listen: 'استمع مع لويين', zonesEyebrow: 'أرشيف المد والجزر / خمس قاعات', zonesTitle: 'خمس طرق إلى هاينان', zonesBody: 'اعبر هاينان بإيقاع المد. تحمل كل قاعة طريقة مختلفة لقراءة المقاطعة.', guideTitle: 'لويين تصغي', guideBody: 'اسأل عن قاعة أو مادة أو إحساس تريد أن تحمله معك.', guideWelcome: 'ابدأ بأي سؤال. سأبقي هذه المحادثة هنا ما دامت نافذة الدردشة مفتوحة.', guideInput: 'اسأل لويين شيئاً...', send: 'إرسال', source: 'مادة مقدمة من المشروع', reality: 'طبقة الواقع', myth: 'أسطورة ShellSong', mock: 'معاينة الدليل المحلي', close: 'إغلاق الدليل', open: 'فتح دليل لويين', footer: 'بوابة حية إلى مقاطعة هاينان.' },
}
