import type { Language, Localized } from './i18n'

export type HainanMapRegionId =
  | 'haikou' | 'sanya' | 'sansha' | 'danzhou' | 'wenchang' | 'qionghai' | 'wanning' | 'wuzhishan' | 'dongfang'
  | 'dingan' | 'tunchang' | 'chengmai' | 'lingao' | 'baisha' | 'changjiang' | 'ledong' | 'lingshui' | 'baoting' | 'qiongzhong'

type FocusId = 'coast' | 'city' | 'heritage' | 'islands' | 'space' | 'forest' | 'rural' | 'craft'

export type HainanMapRegion = {
  id: HainanMapRegionId
  name: Localized
  position: { left: string; top: string; inset?: boolean }
  focus: FocusId[]
  places: Array<{ en: string; zh: string }>
  source: { publisher: string; url: string; checkedAt: string }
}

export const hainanMapCopy: Record<Language, {
  eyebrow: string; title: string; body: string; mapLabel: string; overviewTitle: string; overviewBody: string; focus: string
  recommendations: string; source: string; checked: string; openSource: string; limitation: string; selected: string; instruction: string; closeReading: string
  focusLabels: Record<FocusId, string>
}> = {
  en: {
    eyebrow: 'HAINAN / REGIONAL READING', title: 'An island of many thresholds.', body: 'Select a city or county-level unit to open a source-bounded regional reading card.', mapLabel: 'Regional reading map of Hainan Province', overviewTitle: 'Read Hainan by region.', overviewBody: 'Nineteen city and county-level reading points connect the exhibition to public regional sources. The interactive layer is for cultural orientation only, not surveying or navigation.', focus: 'Reading focus', recommendations: 'Places to explore', source: 'Reviewed public source', checked: 'Checked', openSource: 'Open official source', limitation: 'Verify current access, transport, tickets, opening arrangements, and local conditions directly with the cited official source.', selected: 'Selected region', instruction: 'Choose a region on the map to begin.', closeReading: 'Close region card', focusLabels: { coast: 'Coast', city: 'City', heritage: 'Heritage', islands: 'Sea islands', space: 'Aerospace', forest: 'Forest', rural: 'Rural life', craft: 'Craft' },
  },
  zh: {
    eyebrow: '海南 / 区域阅读', title: '一座岛，许多抵达方式。', body: '选择一个市县级区域，打开有来源边界的地区阅读卡。', mapLabel: '海南省区域阅读地图', overviewTitle: '按区域阅读海南。', overviewBody: '十九个市县级阅读点将展厅叙事连接至各地区公开来源。交互图层仅用于文化导览，不用于测绘或导航。', focus: '阅读焦点', recommendations: '可探索的地点', source: '已核验公共来源', checked: '核验日期', openSource: '打开官方来源', limitation: '当前开放、交通、票务、营业安排和现场条件，请直接以所列官方来源核实。', selected: '当前选择', instruction: '在地图上选择一个区域开始阅读。', closeReading: '关闭地区卡片', focusLabels: { coast: '海岸', city: '城市', heritage: '文化遗产', islands: '海岛群', space: '航天', forest: '森林', rural: '乡村生活', craft: '工艺' },
  },
  id: {
    eyebrow: 'HAINAN / BACAAN WILAYAH', title: 'Satu pulau, banyak ambang.', body: 'Pilih satu kota atau unit setingkat kabupaten untuk membuka kartu bacaan wilayah berbatas sumber.', mapLabel: 'Peta bacaan wilayah Provinsi Hainan', overviewTitle: 'Baca Hainan menurut wilayah.', overviewBody: 'Sembilan belas titik bacaan kota dan kabupaten menghubungkan pameran dengan sumber publik wilayah. Lapisan interaktif ini hanya untuk orientasi budaya, bukan untuk survei atau navigasi.', focus: 'Fokus bacaan', recommendations: 'Tempat untuk dijelajahi', source: 'Sumber publik yang ditinjau', checked: 'Diperiksa', openSource: 'Buka sumber resmi', limitation: 'Verifikasi akses, transportasi, tiket, jadwal buka, dan kondisi setempat langsung pada sumber resmi yang dicantumkan.', selected: 'Wilayah terpilih', instruction: 'Pilih wilayah pada peta untuk memulai.', closeReading: 'Tutup kartu wilayah', focusLabels: { coast: 'Pesisir', city: 'Kota', heritage: 'Warisan', islands: 'Kepulauan', space: 'Antariksa', forest: 'Hutan', rural: 'Kehidupan desa', craft: 'Kerajinan' },
  },
  ja: {
    eyebrow: '海南 / 地域を読む', title: '一つの島、いくつもの入口。', body: '市・県級の地域を選ぶと、出典範囲を明示した地域カードが開きます。', mapLabel: '海南省の地域読解地図', overviewTitle: '地域から海南を読む。', overviewBody: '19 の市・県級の読解点が、展示と地域の公開情報を結びます。インタラクティブ層は文化案内専用で、測量やナビゲーションには使用しません。', focus: '読解の焦点', recommendations: '訪ねる場所', source: '確認済みの公開情報源', checked: '確認日', openSource: '公式情報源を開く', limitation: 'アクセス、交通、チケット、開館予定、現地の状況は、記載の公式情報源で直接確認してください。', selected: '選択中の地域', instruction: '地図上の地域を選んでください。', closeReading: '地域カードを閉じる', focusLabels: { coast: '海岸', city: '都市', heritage: '文化遺産', islands: '島々', space: '宇宙開発', forest: '森林', rural: '農村の暮らし', craft: '工芸' },
  },
  ko: {
    eyebrow: '하이난 / 지역 읽기', title: '하나의 섬, 많은 문턱.', body: '시 또는 현급 지역을 선택하면 출처 범위를 지닌 지역 읽기 카드가 열립니다.', mapLabel: '하이난성 지역 읽기 지도', overviewTitle: '지역으로 하이난을 읽다.', overviewBody: '19개의 시·현급 읽기 지점이 전시와 지역 공개 자료를 연결합니다. 인터랙티브 레이어는 문화 안내용이며 측량이나 내비게이션용이 아닙니다.', focus: '읽기 초점', recommendations: '둘러볼 장소', source: '검토된 공공 출처', checked: '검토일', openSource: '공식 출처 열기', limitation: '접근, 교통, 티켓, 운영 일정 및 현지 상황은 인용된 공식 출처에서 직접 확인하세요.', selected: '선택한 지역', instruction: '지도에서 지역을 선택해 시작하세요.', closeReading: '지역 카드 닫기', focusLabels: { coast: '해안', city: '도시', heritage: '유산', islands: '섬', space: '우주항공', forest: '숲', rural: '농촌 생활', craft: '공예' },
  },
  ru: {
    eyebrow: 'ХАЙНАНЬ / РЕГИОНАЛЬНОЕ ЧТЕНИЕ', title: 'Один остров, множество порогов.', body: 'Выберите город или уездный район, чтобы открыть региональную карточку с ограниченной источниками информацией.', mapLabel: 'Карта регионального чтения провинции Хайнань', overviewTitle: 'Читайте Хайнань по регионам.', overviewBody: 'Девятнадцать городских и уездных точек связывают выставку с региональными публичными источниками. Интерактивный слой предназначен только для культурной ориентации, а не для геодезии или навигации.', focus: 'Фокус чтения', recommendations: 'Места для изучения', source: 'Проверенный публичный источник', checked: 'Проверено', openSource: 'Открыть официальный источник', limitation: 'Актуальный доступ, транспорт, билеты, расписание и местные условия проверяйте непосредственно в указанном официальном источнике.', selected: 'Выбранный регион', instruction: 'Выберите регион на карте, чтобы начать.', closeReading: 'Закрыть региональную карточку', focusLabels: { coast: 'Побережье', city: 'Город', heritage: 'Наследие', islands: 'Острова', space: 'Космос', forest: 'Лес', rural: 'Сельская жизнь', craft: 'Ремесло' },
  },
  ar: {
    eyebrow: 'هاينان / قراءة المناطق', title: 'جزيرة واحدة، ومداخل كثيرة.', body: 'اختر مدينة أو وحدة على مستوى المحافظة لفتح بطاقة قراءة إقليمية مقيّدة بالمصادر.', mapLabel: 'خريطة قراءة مناطق مقاطعة هاينان', overviewTitle: 'اقرأ هاينان عبر مناطقها.', overviewBody: 'تصل تسع عشرة نقطة قراءة على مستوى المدن والمحافظات بين المعرض والمصادر العامة الإقليمية. طبقة التفاعل مخصصة للتوجيه الثقافي فقط وليست للمسح أو الملاحة.', focus: 'محور القراءة', recommendations: 'أماكن للاستكشاف', source: 'مصدر عام مُراجع', checked: 'تاريخ المراجعة', openSource: 'فتح المصدر الرسمي', limitation: 'تحقق مباشرة من الوصول والنقل والتذاكر وساعات العمل والظروف المحلية عبر المصدر الرسمي المذكور.', selected: 'المنطقة المختارة', instruction: 'اختر منطقة على الخريطة للبدء.', closeReading: 'إغلاق بطاقة المنطقة', focusLabels: { coast: 'الساحل', city: 'المدينة', heritage: 'التراث', islands: 'الجزر', space: 'الفضاء', forest: 'الغابة', rural: 'الحياة الريفية', craft: 'الحرف' },
  },
}

const checkedAt = '2026-08-16'

export const hainanMapRegions: HainanMapRegion[] = [
  { id: 'haikou', name: { en: 'Haikou', zh: '海口' }, position: { left: '57.8%', top: '14.4%' }, focus: ['city', 'coast', 'heritage'], places: [{ en: 'Qilou Old Street', zh: '骑楼老街' }, { en: 'Hainan Volcanic Crater Park', zh: '火山口公园' }], source: { publisher: 'Haikou Municipal People’s Government', url: 'https://www.haikou.gov.cn/', checkedAt } },
  { id: 'sanya', name: { en: 'Sanya', zh: '三亚' }, position: { left: '38%', top: '91.2%' }, focus: ['coast', 'city'], places: [{ en: 'Yalong Bay', zh: '亚龙湾' }, { en: 'Tianya Haijiao', zh: '天涯海角' }, { en: 'Nanshan Cultural Tourism Zone', zh: '南山文化旅游区' }], source: { publisher: 'Sanya Municipal People’s Government', url: 'https://www.sanya.gov.cn/', checkedAt } },
  { id: 'sansha', name: { en: 'Sansha', zh: '三沙' }, position: { left: '90.2%', top: '72.7%', inset: true }, focus: ['islands', 'coast'], places: [{ en: 'Yongxing Island', zh: '永兴岛' }, { en: 'Xisha Islands', zh: '西沙群岛' }], source: { publisher: 'Sansha Municipal People’s Government', url: 'https://www.sansha.gov.cn/', checkedAt } },
  { id: 'danzhou', name: { en: 'Danzhou', zh: '儋州' }, position: { left: '40%', top: '36.4%' }, focus: ['heritage', 'coast'], places: [{ en: 'Dongpo Academy', zh: '东坡书院' }, { en: 'Shihua Water Cave', zh: '石花水洞' }], source: { publisher: 'Danzhou Municipal People’s Government', url: 'https://www.danzhou.gov.cn/', checkedAt } },
  { id: 'wenchang', name: { en: 'Wenchang', zh: '文昌' }, position: { left: '75.6%', top: '35.7%' }, focus: ['space', 'coast'], places: [{ en: 'Wenchang Space Launch Site', zh: '文昌航天发射场' }, { en: 'Tongguling', zh: '铜鼓岭' }, { en: 'Dongjiao Coconut Grove', zh: '东郊椰林' }], source: { publisher: 'Wenchang Municipal People’s Government', url: 'https://wenchang.hainan.gov.cn/', checkedAt } },
  { id: 'qionghai', name: { en: 'Qionghai', zh: '琼海' }, position: { left: '66.2%', top: '47.1%' }, focus: ['coast', 'heritage'], places: [{ en: 'Boao', zh: '博鳌' }, { en: 'Wanquan River', zh: '万泉河' }, { en: 'Tanmen', zh: '潭门' }], source: { publisher: 'Qionghai Municipal People’s Government', url: 'https://qionghai.hainan.gov.cn/', checkedAt } },
  { id: 'wanning', name: { en: 'Wanning', zh: '万宁' }, position: { left: '63.4%', top: '67.5%' }, focus: ['coast', 'forest'], places: [{ en: 'Riyue Bay', zh: '日月湾' }, { en: 'Shenzhou Peninsula', zh: '神州半岛' }, { en: 'Xinglong', zh: '兴隆' }], source: { publisher: 'Wanning Municipal People’s Government', url: 'https://wanning.hainan.gov.cn/', checkedAt } },
  { id: 'wuzhishan', name: { en: 'Wuzhishan', zh: '五指山' }, position: { left: '38%', top: '69%' }, focus: ['forest', 'heritage'], places: [{ en: 'Wuzhishan', zh: '五指山' }, { en: 'Maona Village', zh: '毛纳村' }], source: { publisher: 'Hainan Provincial People’s Government', url: 'https://www.hainan.gov.cn/', checkedAt } },
  { id: 'dongfang', name: { en: 'Dongfang', zh: '东方' }, position: { left: '12.4%', top: '55.4%' }, focus: ['coast', 'craft'], places: [{ en: 'Yulinzhou', zh: '鱼鳞洲' }, { en: 'E’xian Ridge', zh: '俄贤岭' }], source: { publisher: 'Dongfang Municipal People’s Government', url: 'https://dongfang.hainan.gov.cn/', checkedAt } },
  { id: 'dingan', name: { en: 'Ding’an', zh: '定安' }, position: { left: '62.3%', top: '30.7%' }, focus: ['rural', 'heritage'], places: [{ en: 'Wenbi Peak', zh: '文笔峰' }, { en: 'Nanli Lake', zh: '南丽湖' }], source: { publisher: 'Hainan Provincial People’s Government', url: 'https://www.hainan.gov.cn/', checkedAt } },
  { id: 'tunchang', name: { en: 'Tunchang', zh: '屯昌' }, position: { left: '54.7%', top: '44.8%' }, focus: ['rural', 'forest'], places: [{ en: 'Fengmu Deer Farm', zh: '枫木鹿场' }, { en: 'Mise Lake', zh: '木色湖' }], source: { publisher: 'Tunchang County People’s Government', url: 'https://tunchang.hainan.gov.cn/', checkedAt } },
  { id: 'chengmai', name: { en: 'Chengmai', zh: '澄迈' }, position: { left: '51.3%', top: '31.5%' }, focus: ['coast', 'rural'], places: [{ en: 'Fushan Coffee Culture Town', zh: '福山咖啡文化风情镇' }, { en: 'Yingbin Peninsula', zh: '盈滨半岛' }], source: { publisher: 'Chengmai County People’s Government', url: 'https://chengmai.hainan.gov.cn/', checkedAt } },
  { id: 'lingao', name: { en: 'Lingao', zh: '临高' }, position: { left: '43%', top: '19.8%' }, focus: ['coast', 'heritage'], places: [{ en: 'Lingao Cape', zh: '临高角' }, { en: 'Jiaolai Village', zh: '加来镇' }], source: { publisher: 'Lingao County People’s Government', url: 'https://lingao.hainan.gov.cn/', checkedAt } },
  { id: 'baisha', name: { en: 'Baisha', zh: '白沙' }, position: { left: '36%', top: '49.3%' }, focus: ['forest', 'rural'], places: [{ en: 'Yinggeling', zh: '鹦哥岭' }, { en: 'Baisha Tea Garden', zh: '白沙茶园' }], source: { publisher: 'Baisha Li Autonomous County People’s Government', url: 'https://baisha.hainan.gov.cn/baisha/index.html', checkedAt } },
  { id: 'changjiang', name: { en: 'Changjiang', zh: '昌江' }, position: { left: '25%', top: '46.6%' }, focus: ['coast', 'forest'], places: [{ en: 'Qizi Bay', zh: '棋子湾' }, { en: 'Bawangling', zh: '霸王岭' }], source: { publisher: 'Changjiang Li Autonomous County People’s Government', url: 'https://changjiang.hainan.gov.cn/', checkedAt } },
  { id: 'ledong', name: { en: 'Ledong', zh: '乐东' }, position: { left: '27.6%', top: '69.1%' }, focus: ['forest', 'coast'], places: [{ en: 'Jianfengling', zh: '尖峰岭' }, { en: 'Yinggehai', zh: '莺歌海' }], source: { publisher: 'Ledong Li Autonomous County People’s Government', url: 'https://ledong.hainan.gov.cn/', checkedAt } },
  { id: 'lingshui', name: { en: 'Lingshui', zh: '陵水' }, position: { left: '52.7%', top: '79.9%' }, focus: ['coast', 'islands'], places: [{ en: 'Fenjiezhou Island', zh: '分界洲岛' }, { en: 'Nanwan Monkey Island', zh: '南湾猴岛' }, { en: 'Clear Water Bay', zh: '清水湾' }], source: { publisher: 'Lingshui Li Autonomous County People’s Government', url: 'https://lingshui.hainan.gov.cn/', checkedAt } },
  { id: 'baoting', name: { en: 'Baoting', zh: '保亭' }, position: { left: '43.6%', top: '73.9%' }, focus: ['forest', 'heritage'], places: [{ en: 'Qixianling', zh: '七仙岭' }, { en: 'Betel Nut Valley', zh: '槟榔谷' }], source: { publisher: 'Baoting Li and Miao Autonomous County People’s Government', url: 'https://baoting.hainan.gov.cn/', checkedAt } },
  { id: 'qiongzhong', name: { en: 'Qiongzhong', zh: '琼中' }, position: { left: '53.5%', top: '60%' }, focus: ['forest', 'rural'], places: [{ en: 'Baihua Ridge', zh: '百花岭' }, { en: 'Yinggeling', zh: '鹦哥岭' }], source: { publisher: 'Qiongzhong Li and Miao Autonomous County People’s Government', url: 'https://qiongzhong.hainan.gov.cn/', checkedAt } },
]
