import type { Language } from './data'
import { assertLocalizationTree, type Localized } from './i18n'

export type TropicalExhibit = {
  id: string
  title: Localized
  introduction: Localized
  note: Localized
  asset: string
  fallback: string
}

export const tropicalReferenceImage = '/assets/3d/tropical/tropical-island-reference.png'

export const tropicalExhibits: TropicalExhibit[] = [
  { id: 'waterline-play', title: { en: 'Waterline Play', zh: '水岸活动观察', id: 'Permainan Garis Air', ja: '水際の遊び', ko: '물가 놀이 관찰', ru: 'Игра у кромки воды', ar: 'لعب عند خط الماء' }, introduction: { en: 'A project-supplied still life for reading floating forms, safety colours and the rhythm between sand and water.', zh: '项目提供的静物图像，用于观看漂浮形态、安全色彩，以及沙滩与海水之间的节奏。', id: 'Benda mati dari proyek untuk membaca bentuk terapung, warna keselamatan, dan irama antara pasir dan air.', ja: '浮かぶ形、安全色、砂と水のリズムを読むためのプロジェクト提供静物です。', ko: '떠 있는 형태와 안전색, 모래와 물 사이의 리듬을 읽는 프로젝트 제공 정물입니다.', ru: 'Натюрморт проекта для чтения плавающих форм, сигнальных цветов и ритма между песком и водой.', ar: 'مشهد ثابت قدمه المشروع لقراءة الأشكال العائمة وألوان السلامة وإيقاع الرمل والماء.' }, note: { en: 'This is a curatorial image, not a tourism service, equipment catalogue, rental offer or activity schedule.', zh: '这是一张策展图像，不是旅游服务、设备目录、租赁信息或活动安排。', id: 'Gambar kuratorial, bukan layanan wisata, katalog peralatan, tawaran sewa, atau jadwal kegiatan.', ja: 'キュレーション画像であり、旅行サービス、機材カタログ、レンタル、活動予定ではありません。', ko: '큐레이션 이미지이며 관광 서비스, 장비 목록, 대여 제안 또는 활동 일정이 아닙니다.', ru: 'Кураторское изображение, а не туристическая услуга, каталог оборудования, аренда или расписание.', ar: 'صورة تنسيقية وليست خدمة سياحية أو كتالوج معدات أو عرض إيجار أو جدول نشاط.' }, asset: '/assets/exhibits/tropical/waterline-play.png', fallback: tropicalReferenceImage },
  { id: 'shore-rest', title: { en: 'Shore Rest', zh: '沙滩休憩观察', id: 'Istirahat di Pantai', ja: '浜辺の休息', ko: '해변 휴식 관찰', ru: 'Отдых у берега', ar: 'استراحة على الشاطئ' }, introduction: { en: 'A project-supplied beach composition that invites attention to shade, rest and the changing edge of the tide.', zh: '项目提供的海滩构图，邀请观者观察遮荫、停留，以及潮汐不断变化的边界。', id: 'Komposisi pantai dari proyek yang mengajak memperhatikan teduh, rehat, dan tepi pasang yang berubah.', ja: '日陰と休息、変化する潮の縁に目を向けるプロジェクト提供の浜辺構図です。', ko: '그늘과 휴식, 변하는 조수의 경계에 주목하게 하는 프로젝트 제공 해변 구성입니다.', ru: 'Пляжная композиция проекта, приглашающая заметить тень, отдых и меняющуюся кромку прилива.', ar: 'تكوين شاطئي قدمه المشروع يلفت الانتباه إلى الظل والراحة وحافة المد المتغيرة.' }, note: { en: 'It does not identify a real resort, public facility, opening time, booking channel or current beach condition.', zh: '它不指向真实度假区、公共设施、开放时间、预订渠道或当前海滩状况。', id: 'Tidak mengidentifikasi resor, fasilitas publik, jam buka, kanal pemesanan, atau kondisi pantai saat ini.', ja: '実在のリゾート、公共施設、開場時間、予約窓口、現在の浜辺の状態を示すものではありません。', ko: '실제 리조트, 공공 시설, 운영 시간, 예약 채널 또는 현재 해변 상태를 특정하지 않습니다.', ru: 'Не указывает на реальный курорт, объект, часы работы, канал бронирования или текущее состояние пляжа.', ar: 'لا يحدد منتجعاً حقيقياً أو مرفقاً عاماً أو وقت فتح أو قناة حجز أو حالة الشاطئ الحالية.' }, asset: '/assets/exhibits/tropical/shore-rest.png', fallback: tropicalReferenceImage },
  { id: 'canopy-path', title: { en: 'Canopy Path', zh: '海岛步道观察', id: 'Jalur Kanopi', ja: '島の木陰道', ko: '섬의 녹음길 관찰', ru: 'Тропа под кронами', ar: 'ممر تحت الأشجار' }, introduction: { en: 'A project-supplied path study for reading layered greenery, handmade markers and the invitation to move slowly.', zh: '项目提供的步道图像，用于观看层叠绿意、手工装饰与慢行的邀请。', id: 'Studi jalur dari proyek untuk membaca lapisan hijau, penanda buatan tangan, dan ajakan berjalan pelan.', ja: '重なる緑、手作りの目印、ゆっくり歩く誘いを読むプロジェクト提供の道の研究です。', ko: '겹겹의 초록과 손으로 만든 표식, 천천히 움직이라는 초대를 읽는 프로젝트 제공 길 연구입니다.', ru: 'Исследование тропы проекта для чтения слоёв зелени, рукотворных знаков и приглашения идти медленно.', ar: 'دراسة ممر قدمها المشروع لقراءة طبقات الخضرة والعلامات اليدوية والدعوة إلى السير ببطء.' }, note: { en: 'This is not a map, route recommendation, safety notice or verified description of a specific island trail.', zh: '这不是地图、路线推荐、安全提示，也不是对某条真实海岛步道的核验描述。', id: 'Bukan peta, rekomendasi rute, pemberitahuan keselamatan, atau deskripsi terverifikasi tentang jalur pulau tertentu.', ja: '地図、ルート案内、安全通知、特定の島の道の確認済み説明ではありません。', ko: '지도, 경로 추천, 안전 안내 또는 특정 섬 산책로의 검증된 설명이 아닙니다.', ru: 'Это не карта, рекомендация маршрута, уведомление о безопасности или проверенное описание конкретной островной тропы.', ar: 'ليس خريطة أو توصية مسار أو إشعار سلامة أو وصفاً متحققاً لمسار جزيرة محدد.' }, asset: '/assets/exhibits/tropical/canopy-path.png', fallback: tropicalReferenceImage },
  { id: 'tropical-table', title: { en: 'Tropical Table', zh: '热带餐桌观察', id: 'Meja Tropis', ja: '熱帯の食卓', ko: '열대의 식탁 관찰', ru: 'Тропический стол', ar: 'مائدة استوائية' }, introduction: { en: 'A project-supplied table scene for noticing colour, texture and the social feeling of sharing a coastal meal.', zh: '项目提供的餐桌场景，用于观察色彩、质感，以及海岸共享餐食的社交感受。', id: 'Adegan meja dari proyek untuk memperhatikan warna, tekstur, dan rasa sosial berbagi hidangan pesisir.', ja: '色と質感、海辺の食事を分かち合う社会的な感覚に気づくためのプロジェクト提供の食卓です。', ko: '색과 질감, 해안 식사를 나누는 사회적 감각을 살피는 프로젝트 제공 식탁 장면입니다.', ru: 'Сцена стола проекта для наблюдения за цветом, фактурой и общим чувством прибрежной трапезы.', ar: 'مشهد مائدة قدمه المشروع لملاحظة اللون والملمس والإحساس الاجتماعي بمشاركة وجبة ساحلية.' }, note: { en: 'The image is not a menu, restaurant listing, price statement, food-safety claim or promise of availability.', zh: '这不是菜单、餐厅信息、价格说明、食品安全声明或供应承诺。', id: 'Gambar ini bukan menu, daftar restoran, pernyataan harga, klaim keamanan pangan, atau jaminan ketersediaan.', ja: 'メニュー、レストラン案内、価格表示、食品安全の主張、提供保証ではありません。', ko: '메뉴, 식당 목록, 가격 안내, 식품 안전 주장 또는 이용 가능성 보장이 아닙니다.', ru: 'Изображение не является меню, списком ресторанов, заявлением о цене, гарантией безопасности или доступности.', ar: 'الصورة ليست قائمة طعام أو دليلاً لمطعم أو بيان سعر أو ادعاء سلامة غذاء أو ضمان توافر.' }, asset: '/assets/exhibits/tropical/tropical-table.png', fallback: tropicalReferenceImage },
]
assertLocalizationTree(tropicalExhibits, 'tropical hall data')
